dependencies:
  - python==3.9.4
  - pip==22.1.1
  - pip:
    - aepsych==0.2.0
    - aepsych-client==0.1.1
    - bqplot
    - ipympl
    - ipyvolume
    - scipy
    - voila
    - ipywidgets==7.7.1
    - jupyterlab>=3.1
