name: Update main version to match release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build distribution from release branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: "release"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install repo and get version
        run: |
          python3 -m pip install .
          echo "version=$(python -c "import aepsych; print(aepsych.version.__version__)")" >> "$GITHUB_ENV"

      - uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Edit main version with dev appended
        run: |
          sed -i "s/^__version__ .*/__version__ = \""$version"+dev\"/" aepsych/version.py

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update main version to ${{ version }}+dev